name: Locales
on: [push, pull_request]
jobs:
  locale-check:
    name: Locale check
    runs-on: ubuntu-latest
    if: ${{ vars.APK_ONLY == '' }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install gettext qt6-base-dev qt6-tools-dev qt6-l10n-tools qtchooser

    - name: Check that .po files are up to date
      run: |
        qtchooser -install qt6 $(which qmake6)
        export QT_SELECT=qt6
        tools/check_messages.sh
